
from models import db, Category, Store, Product, User
from flask_bcrypt import generate_password_hash

def seed_data():
    if Category.query.first():
        return

    cats = [
        Category(name="Leafy Greens", icon="🥬"),
        Category(name="Root Vegetables", icon="🥕"),
        Category(name="Cruciferous", icon="🥦"),
        Category(name="Alliums", icon="🧅"),
        Category(name="Nightshades", icon="🍅"),
        Category(name="Legumes", icon="🫘"),
        Category(name="Gourds", icon="🎃"),
        Category(name="Herbs & Spices", icon="🌿"),
        Category(name="Exotic & Rare", icon="🌶️"),
        Category(name="Seasonal", icon="🌾"),
    ]
    db.session.add_all(cats)
    db.session.flush()

    stores = [
        Store(name="Fresh Harvest - Indiranagar", location="No. 12, 100 Feet Road, Indiranagar, Bengaluru, Karnataka 560038", phone="+91 80 4112 3344", email="indiranagar@freshharvest.in", rating=4.8),
        Store(name="Organic India Store - Koramangala", location="No. 45, 5th Block, Koramangala, Bengaluru, Karnataka 560095", phone="+91 80 4223 5566", email="koramangala@organicindia.com", rating=4.7),
        Store(name="Nature's Basket - Bandra West", location="Shop 3, Linking Road, Bandra West, Mumbai, Maharashtra 400050", phone="+91 22 2640 7788", email="bandra@naturesbasket.in", rating=4.6),
        Store(name="Sabzi Mandi Fresh - Connaught Place", location="Block A, Connaught Place, New Delhi, Delhi 110001", phone="+91 11 2341 9900", email="cp@sabzimandifresh.com", rating=4.5),
        Store(name="Green Valley Organics - Jubilee Hills", location="Road No. 36, Jubilee Hills, Hyderabad, Telangana 500033", phone="+91 40 6677 8899", email="jubileehills@greenvalleyorganics.in", rating=4.7),
    ]
    db.session.add_all(stores)
    db.session.flush()

    products = [
        Product(name="Baby Spinach", description="Tender baby spinach leaves freshly harvested from farms in Ooty. Rich in iron, folate and vitamins A, C and K. Perfect for salads, smoothies, dals and sabzis. No pesticides used.", price=45, original_price=60, unit="250g", stock=300, emoji="🥬", image_url="https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&q=80", category_id=cats[0].id, store_id=stores[0].id, is_organic=True, is_featured=True, rating=4.8, review_count=1243, tags="salad,smoothie,iron,vitamins,ooty"),
        Product(name="Methi (Fenugreek Leaves)", description="Fresh methi leaves with a characteristic slightly bitter taste. Grown in Punjab. Excellent for methi paratha, dal methi and aloo methi. High in fibre and minerals.", price=20, unit="bunch", stock=400, emoji="🌿", image_url="https://images.unsplash.com/photo-1503764654157-72d979d9af2f?w=600&q=80", category_id=cats[0].id, store_id=stores[3].id, rating=4.7, review_count=892, tags="paratha,dal,punjab,fibre"),
        Product(name="Palak (Spinach)", description="Classic Indian palak, the star of palak paneer. Broad flat leaves freshly cut from local farms in Nasik. Blanches beautifully and retains vibrant green colour.", price=25, unit="bunch", stock=500, emoji="🥬", image_url="https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?w=600&q=80", category_id=cats[0].id, store_id=stores[2].id, is_organic=True, is_featured=True, rating=4.9, review_count=2341, tags="paneer,dal,nasik,iron"),
        Product(name="Curry Leaves (Kadi Patta)", description="Fresh aromatic curry leaves from Tamil Nadu. Essential in South Indian tadkas, chutneys and rice dishes. Adds an unmistakable fragrance to any dish.", price=10, unit="bunch", stock=600, emoji="🌿", image_url="https://images.unsplash.com/photo-1455642305367-68834a1da7ab?w=600&q=80", category_id=cats[0].id, store_id=stores[4].id, is_featured=True, rating=4.9, review_count=3421, tags="tadka,south-indian,tamil-nadu,fragrant"),
        Product(name="Carrot (Gajar)", description="Sweet crunchy carrots from Himachal Pradesh. Bright orange, thick and naturally sweet. Perfect for gajar ka halwa, salads, juices and sabzis. Loaded with beta-carotene.", price=40, original_price=55, unit="kg", stock=800, emoji="🥕", image_url="https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=600&q=80", category_id=cats[1].id, store_id=stores[0].id, is_organic=True, is_featured=True, rating=4.9, review_count=4521, tags="halwa,juice,himachal,beta-carotene,sweet"),
        Product(name="Beetroot (Chukandar)", description="Deep red earthy beetroots from Maharashtra. Rich in nitrates, folate and manganese. Great for beet sabzi, raita, salads and fresh juice.", price=35, unit="kg", stock=400, emoji="🔴", image_url="https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?w=600&q=80", category_id=cats[1].id, store_id=stores[2].id, rating=4.7, review_count=1234, tags="raita,juice,salad,maharashtra,nitrates"),
        Product(name="Radish (Mooli)", description="Crisp white radishes freshly pulled from fields in Rajasthan. Mild and peppery, perfect for mooli paratha, salads and mooli sabzi. Essential in winters.", price=20, unit="kg", stock=500, emoji="⚪", image_url="https://images.unsplash.com/photo-1592921870583-aeafb0639ffe?w=600&q=80", category_id=cats[1].id, store_id=stores[3].id, rating=4.6, review_count=876, tags="paratha,rajasthan,winter,peppery"),
        Product(name="Sweet Potato (Shakarkandi)", description="Orange-fleshed sweet potatoes from Odisha. Naturally sweet and caramelise beautifully when roasted. Excellent source of vitamin A. Popular street food roasted on coal.", price=50, unit="kg", stock=300, emoji="🍠", image_url="https://images.unsplash.com/photo-1596097635121-14b63b7a0c19?w=600&q=80", category_id=cats[1].id, store_id=stores[1].id, is_featured=True, rating=4.8, review_count=1876, tags="roast,odisha,vitamin-A,street-food,sweet"),
        Product(name="Broccoli", description="Firm bright green broccoli heads from Himachal Pradesh. Excellent stir-fried, steamed, in soups or eaten raw. Superfood loaded with vitamins.", price=80, original_price=100, unit="piece", stock=400, emoji="🥦", image_url="https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=600&q=80", category_id=cats[2].id, store_id=stores[1].id, is_organic=True, is_featured=True, rating=4.8, review_count=2341, tags="superfood,himachal,stir-fry,soup,steam"),
        Product(name="Cauliflower (Phool Gobhi)", description="Large white cauliflower from Punjab, the king of winter vegetables. Perfect for aloo gobi, gobi manchurian, gobi paratha and pakoras.", price=40, unit="piece", stock=600, emoji="⬜", image_url="https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=600&q=80", category_id=cats[2].id, store_id=stores[3].id, is_featured=True, rating=4.9, review_count=3456, tags="aloo-gobi,manchurian,paratha,punjab,winter"),
        Product(name="Cabbage (Patta Gobhi)", description="Crisp green cabbage from Himachal Pradesh. Fresh and tightly packed. Excellent for cabbage sabzi, stir fry, salads and used in momos filling.", price=25, unit="piece", stock=700, emoji="🥬", image_url="https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80", category_id=cats[2].id, store_id=stores[4].id, rating=4.7, review_count=2123, tags="sabzi,momo,stir-fry,himachal,salad"),
        Product(name="Onion (Pyaz)", description="Premium Nashik red onions, the backbone of Indian cooking. Sharp pungent flavour that mellows beautifully when cooked. Every Indian dish starts here.", price=35, unit="kg", stock=2000, emoji="🧅", image_url="https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&q=80", category_id=cats[3].id, store_id=stores[2].id, is_featured=True, rating=4.9, review_count=8765, tags="nashik,essential,indian-cooking,curry,dal"),
        Product(name="Garlic (Lahsun)", description="Large-cloved garlic from Madhya Pradesh. Intensely aromatic with a bold flavour. Sun-dried for enhanced shelf life. Used in every Indian kitchen daily.", price=60, unit="250g", stock=1000, emoji="🧄", image_url="https://images.unsplash.com/photo-1471943038886-2e8393ea0b9b?w=600&q=80", category_id=cats[3].id, store_id=stores[1].id, is_organic=True, is_featured=True, rating=4.9, review_count=6543, tags="tadka,MP,aromatic,essential,immunity"),
        Product(name="Ginger (Adrak)", description="Fresh young ginger from Kerala and Meghalaya. Fiery and aromatic, essential in chai, curries, marinades and chutneys. Anti-inflammatory superfood.", price=40, unit="250g", stock=800, emoji="🫚", image_url="https://images.unsplash.com/photo-1571680322279-a226e6a4cc2a?w=600&q=80", category_id=cats[3].id, store_id=stores[4].id, is_featured=True, rating=4.8, review_count=4321, tags="chai,kerala,meghalaya,immunity,anti-inflammatory"),
        Product(name="Spring Onion (Hara Pyaz)", description="Fresh green spring onions with both bulb and greens. Mild and versatile, used in Chinese-Indian dishes, dosas and raitas.", price=15, unit="bunch", stock=600, emoji="🌿", image_url="https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=600&q=80", category_id=cats[3].id, store_id=stores[3].id, rating=4.6, review_count=1234, tags="chinese,dosa,raita,mild,fresh"),
        Product(name="Tomato (Tamatar)", description="Firm ripe tomatoes from Himachal Pradesh and Nasik. The foundation of Indian cooking. Rich in lycopene and vitamin C. Perfect for curries, chutneys and rasam.", price=30, original_price=45, unit="kg", stock=1500, emoji="🍅", image_url="https://images.unsplash.com/photo-1546094096-0df4bcabd337?w=600&q=80", category_id=cats[4].id, store_id=stores[1].id, is_organic=True, is_featured=True, rating=4.9, review_count=7654, tags="curry,rasam,chutney,lycopene,nasik,essential"),
        Product(name="Green Chilli (Hari Mirch)", description="Medium-hot green chillies from Andhra Pradesh. The fiery soul of Indian cooking. Used fresh in tadkas, chutneys, stuffed mirchi bajji and pickles.", price=20, unit="100g", stock=800, emoji="🌶️", image_url="https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=600&q=80", category_id=cats[4].id, store_id=stores[4].id, is_featured=True, rating=4.8, review_count=3456, tags="andhra,spicy,tadka,pickle,bajji,essential"),
        Product(name="Brinjal (Baingan)", description="Glossy purple brinjals from Rajasthan and Gujarat. Perfect for baingan bharta, brinjal curry, stuffed baingan and begun bhaja. Smoky when roasted.", price=35, unit="kg", stock=400, emoji="🍆", image_url="https://images.unsplash.com/photo-1615484477778-ca3b77940c25?w=600&q=80", category_id=cats[4].id, store_id=stores[3].id, is_featured=True, rating=4.7, review_count=2345, tags="bharta,rajasthan,smoky,roast,gujarat"),
        Product(name="Potato (Aloo)", description="Premium Agra potatoes, the most versatile vegetable in Indian cooking. From aloo paratha to dum aloo to samosa filling. Always fresh, never from cold storage.", price=30, unit="kg", stock=3000, emoji="🥔", image_url="https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&q=80", category_id=cats[4].id, store_id=stores[2].id, is_featured=True, rating=4.9, review_count=12345, tags="aloo,agra,paratha,samosa,dum-aloo,essential"),
        Product(name="Capsicum (Shimla Mirch)", description="Colourful bell peppers in red, yellow and green from Himachal Pradesh. Crunchy and sweet, perfect for paneer capsicum and kadai preparations.", price=60, unit="3 pieces", stock=500, emoji="🫑", image_url="https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&q=80", category_id=cats[4].id, store_id=stores[0].id, is_organic=True, rating=4.7, review_count=1876, tags="paneer,kadai,himachal,stuffed,colorful"),
        Product(name="Green Peas (Matar)", description="Fresh shelled green peas from Punjab during winter season. Sweet and tender. Essential for matar paneer, gajar matar and pulao.", price=60, unit="500g", stock=400, emoji="🫛", image_url="https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=600&q=80", category_id=cats[5].id, store_id=stores[3].id, is_featured=True, rating=4.9, review_count=3456, tags="matar-paneer,punjab,seasonal,winter,sweet"),
        Product(name="French Beans", description="Tender crisp French beans from Ooty. Snaps cleanly when fresh. Perfect for beans poriyal, stir fry and mixed vegetable curry.", price=55, unit="500g", stock=300, emoji="🫘", image_url="https://images.unsplash.com/photo-1567375698348-5d9d5ae99de0?w=600&q=80", category_id=cats[5].id, store_id=stores[1].id, is_organic=True, rating=4.7, review_count=1234, tags="poriyal,ooty,stir-fry,crisp,fibre"),
        Product(name="Bottle Gourd (Lauki)", description="Fresh light green lauki from Maharashtra, prized in Ayurveda. Cooling and easy to digest. Used in lauki ki sabzi, halwa, raita and kofta.", price=25, unit="piece", stock=600, emoji="🫙", image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&q=80", category_id=cats[6].id, store_id=stores[2].id, is_featured=True, rating=4.7, review_count=2345, tags="ayurveda,maharashtra,halwa,kofta,cooling"),
        Product(name="Cucumber (Kheera)", description="Cool crisp cucumbers from Karnataka. Refreshing and hydrating. Eaten raw with chaat masala, in raita and salads. 95 percent water content.", price=20, unit="piece", stock=800, emoji="🥒", image_url="https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=600&q=80", category_id=cats[6].id, store_id=stores[1].id, is_featured=True, rating=4.8, review_count=3456, tags="raita,chaat,karnataka,refreshing,summer"),
        Product(name="Bitter Gourd (Karela)", description="Knobbly bitter gourds from Andhra Pradesh. Medicinal properties for blood sugar regulation and liver cleanse. Stuffed karela is a delicacy.", price=40, unit="500g", stock=300, emoji="💚", image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&q=80", category_id=cats[6].id, store_id=stores[4].id, rating=4.4, review_count=1234, tags="andhra,medicinal,blood-sugar,liver,stuffed"),
        Product(name="Coriander (Dhaniya)", description="Fresh aromatic coriander from Punjab, the most used herb in Indian cooking. Essential in chutneys, garnishes, raitas and biryanis.", price=10, unit="bunch", stock=1000, emoji="🌿", image_url="https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&q=80", category_id=cats[7].id, store_id=stores[3].id, is_featured=True, rating=4.9, review_count=5432, tags="chutney,garnish,punjab,biryani,essential"),
        Product(name="Mint (Pudina)", description="Fresh spearmint from Himachal Pradesh. Cool and refreshing, essential for pudina chutney, raita, biryanis and chaas.", price=10, unit="bunch", stock=800, emoji="🌿", image_url="https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600&q=80", category_id=cats[7].id, store_id=stores[0].id, is_organic=True, is_featured=True, rating=4.9, review_count=4321, tags="chutney,raita,biryani,chaas,himachal"),
        Product(name="Baby Corn", description="Tender miniature corn cobs harvested before maturity. Popular in Indo-Chinese cuisine. Adds crunch to fried rice, Manchurian and soups.", price=60, unit="200g", stock=250, emoji="🌽", image_url="https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=600&q=80", category_id=cats[8].id, store_id=stores[0].id, rating=4.7, review_count=1234, tags="manchurian,fried-rice,chinese,soup,crunch"),
        Product(name="Cherry Tomatoes", description="Sweet colourful cherry tomatoes from poly-houses in Himachal. Burst with flavour when bitten. Perfect for salads, pasta and bruschetta.", price=90, original_price=110, unit="250g", stock=300, emoji="🍒", image_url="https://images.unsplash.com/photo-1561136594-7f68413baa99?w=600&q=80", category_id=cats[8].id, store_id=stores[0].id, is_organic=True, is_featured=True, rating=4.9, review_count=2345, tags="salad,pasta,himachal,sweet,snack"),
        Product(name="Zucchini", description="Green and yellow zucchinis from farms in Pune and Bangalore. Mild and versatile, perfect for stir fries, pasta substitutes and continental cooking.", price=80, unit="500g", stock=200, emoji="🥒", image_url="https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&q=80", category_id=cats[8].id, store_id=stores[1].id, is_organic=True, rating=4.6, review_count=765, tags="pasta,grill,pune,continental,mild"),
        Product(name="Corn (Makka)", description="Fresh sweet corn from Bihar and UP. Best enjoyed roasted on coal with lemon and chaat masala. Peak season June to August.", price=15, unit="cob", stock=800, emoji="🌽", image_url="https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=600&q=80", category_id=cats[9].id, store_id=stores[3].id, is_featured=True, rating=4.9, review_count=4567, tags="bihar,UP,roast,chaat,seasonal,monsoon"),
        Product(name="Raw Mango (Kaccha Aam)", description="Firm sour raw mangoes from Andhra Pradesh and Maharashtra. Essential for aam panna, raw mango chutney and pickle. Limited summer availability.", price=50, unit="kg", stock=200, emoji="🥭", image_url="https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&q=80", category_id=cats[9].id, store_id=stores[4].id, is_featured=True, rating=4.8, review_count=2345, tags="aam-panna,pickle,andhra,summer,seasonal"),
        Product(name="Drumstick (Sahjan)", description="Long slender drumsticks from Tamil Nadu. Moringa superfood. Intensely nutritious pods used in sambar, drumstick sabzi and soup.", price=30, unit="4 pieces", stock=300, emoji="🌿", image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&q=80", category_id=cats[9].id, store_id=stores[4].id, rating=4.8, review_count=1876, tags="moringa,sambar,tamil-nadu,superfood,nutritious"),
    ]
    db.session.add_all(products)

    admin = User(name="Karan Admin", email="admin@vegestore.in", password=generate_password_hash("admin123").decode("utf-8"))
    db.session.add(admin)
    db.session.commit()
    print(f"Seeded {len(products)} real Indian products!")
